/**
 * Plan Approval Dialog Component
 *
 * Modal for reviewing and approving/rejecting generated plans.
 * Displays the plan content with approve/reject actions and
 * feedback textarea for rejection.
 *
 * Requirements: 3.6, 3.7, 3.8
 */

import { useState, useCallback } from 'react'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from 'renderer/components/ui/dialog'
import { Button } from 'renderer/components/ui/button'
import { Textarea } from 'renderer/components/ui/textarea'
import { Label } from 'renderer/components/ui/label'
import { Badge } from 'renderer/components/ui/badge'
import { ScrollArea } from 'renderer/components/ui/scroll-area'
import { SimpleMarkdown } from 'renderer/components/ui/simple-markdown'
import {
  IconCheck,
  IconX,
  IconLoader2,
  IconFileText,
  IconAlertTriangle,
} from '@tabler/icons-react'
import type { PlanSpec, AgentTask } from 'shared/ai-types'

interface PlanApprovalDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  task: AgentTask | null
  onApprove: (taskId: string) => Promise<void>
  onReject: (taskId: string, feedback: string) => Promise<void>
}

/**
 * Get badge variant based on plan status
 */
function getPlanStatusVariant(
  status: PlanSpec['status']
): 'default' | 'secondary' | 'destructive' | 'outline' {
  switch (status) {
    case 'approved':
      return 'default'
    case 'rejected':
      return 'destructive'
    case 'generating':
      return 'secondary'
    default:
      return 'outline'
  }
}

/**
 * Get human-readable status label
 */
function getPlanStatusLabel(status: PlanSpec['status']): string {
  switch (status) {
    case 'pending':
      return 'Pending'
    case 'generating':
      return 'Generating...'
    case 'generated':
      return 'Awaiting Review'
    case 'approved':
      return 'Approved'
    case 'rejected':
      return 'Rejected'
    default:
      return status
  }
}

export function PlanApprovalDialog({
  open,
  onOpenChange,
  task,
  onApprove,
  onReject,
}: PlanApprovalDialogProps): React.JSX.Element {
  const [feedback, setFeedback] = useState('')
  const [isApproving, setIsApproving] = useState(false)
  const [isRejecting, setIsRejecting] = useState(false)
  const [showFeedbackInput, setShowFeedbackInput] = useState(false)

  const planSpec = task?.planSpec

  const handleApprove = useCallback(async () => {
    if (!task) return

    setIsApproving(true)
    try {
      await onApprove(task.id)
      onOpenChange(false)
    } catch (error) {
      console.error('Failed to approve plan:', error)
    } finally {
      setIsApproving(false)
    }
  }, [task, onApprove, onOpenChange])

  const handleReject = useCallback(async () => {
    if (!task) return

    if (!showFeedbackInput) {
      setShowFeedbackInput(true)
      return
    }

    if (!feedback.trim()) {
      return
    }

    setIsRejecting(true)
    try {
      await onReject(task.id, feedback.trim())
      setFeedback('')
      setShowFeedbackInput(false)
      onOpenChange(false)
    } catch (error) {
      console.error('Failed to reject plan:', error)
    } finally {
      setIsRejecting(false)
    }
  }, [task, feedback, showFeedbackInput, onReject, onOpenChange])

  const handleClose = useCallback(() => {
    setFeedback('')
    setShowFeedbackInput(false)
    onOpenChange(false)
  }, [onOpenChange])

  const canApprove = planSpec?.status === 'generated'
  const canReject = planSpec?.status === 'generated'

  return (
    <Dialog onOpenChange={handleClose} open={open}>
      <DialogContent className="sm:max-w-2xl max-h-[80vh] flex flex-col">
        <DialogHeader>
          <div className="flex items-center gap-2">
            <IconFileText className="h-5 w-5 text-primary" />
            <DialogTitle>Review Generated Plan</DialogTitle>
          </div>
          <DialogDescription>
            Review the plan generated by the agent before proceeding with
            implementation.
          </DialogDescription>
        </DialogHeader>

        {task && planSpec && (
          <div className="flex-1 min-h-0 space-y-4">
            {/* Task info header */}
            <div className="flex items-center justify-between gap-2 rounded-lg border bg-muted/30 p-3">
              <div className="flex-1 min-w-0">
                <p className="text-sm font-medium truncate">
                  {task.description}
                </p>
                <p className="text-xs text-muted-foreground">
                  Planning Mode:{' '}
                  <span className="capitalize">{task.planningMode}</span>
                </p>
              </div>
              <Badge variant={getPlanStatusVariant(planSpec.status)}>
                {getPlanStatusLabel(planSpec.status)}
              </Badge>
            </div>

            {/* Plan content */}
            {planSpec.content ? (
              <ScrollArea className="flex-1 rounded-lg border bg-muted/20 p-4 max-h-[40vh]">
                <SimpleMarkdown
                  className="text-sm"
                  content={planSpec.content}
                />
              </ScrollArea>
            ) : (
              <div className="flex items-center justify-center rounded-lg border bg-muted/20 p-8">
                {planSpec.status === 'generating' ? (
                  <div className="flex items-center gap-2 text-muted-foreground">
                    <IconLoader2 className="h-5 w-5 animate-spin" />
                    <span>Generating plan...</span>
                  </div>
                ) : (
                  <div className="flex items-center gap-2 text-muted-foreground">
                    <IconAlertTriangle className="h-5 w-5" />
                    <span>No plan content available</span>
                  </div>
                )}
              </div>
            )}

            {/* Plan metadata */}
            {planSpec.generatedAt && (
              <p className="text-xs text-muted-foreground">
                Generated at: {new Date(planSpec.generatedAt).toLocaleString()}
                {planSpec.version > 1 && ` (Version ${planSpec.version})`}
              </p>
            )}

            {/* Feedback input for rejection */}
            {showFeedbackInput && (
              <div className="space-y-2">
                <Label htmlFor="feedback">
                  Feedback for Regeneration
                  <span className="text-destructive ml-1">*</span>
                </Label>
                <Textarea
                  id="feedback"
                  onChange={e => setFeedback(e.target.value)}
                  placeholder="Explain what changes you'd like to see in the plan..."
                  rows={3}
                  value={feedback}
                />
                <p className="text-xs text-muted-foreground">
                  Your feedback will be used to regenerate the plan with
                  improvements.
                </p>
              </div>
            )}
          </div>
        )}

        <DialogFooter className="gap-2">
          {showFeedbackInput && (
            <Button
              onClick={() => {
                setShowFeedbackInput(false)
                setFeedback('')
              }}
              variant="ghost"
            >
              Cancel
            </Button>
          )}

          <Button
            disabled={!canReject || isApproving || isRejecting}
            onClick={handleReject}
            variant="outline"
          >
            {isRejecting ? (
              <>
                <IconLoader2 className="mr-2 h-4 w-4 animate-spin" />
                Rejecting...
              </>
            ) : (
              <>
                <IconX className="mr-2 h-4 w-4" />
                {showFeedbackInput ? 'Submit Feedback' : 'Reject'}
              </>
            )}
          </Button>

          <Button
            disabled={!canApprove || isApproving || isRejecting}
            onClick={handleApprove}
          >
            {isApproving ? (
              <>
                <IconLoader2 className="mr-2 h-4 w-4 animate-spin" />
                Approving...
              </>
            ) : (
              <>
                <IconCheck className="mr-2 h-4 w-4" />
                Approve Plan
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
